### ISSUE TITLE
Pages revamp

### ISSUE THREAD

**Issue by skypher** [otherjoel/thenotepad#11]
Let me know if you disagree, but I think the pages mechanism need a revamp.

Right now, pages live in the top-level directory and are hardcoded in the link bar and the makefile. I think they need to go in their own dir and then get collected automagically.

I might do this myself at some point.

**Comment by otherjoel** [comment]
For this repo, no. For me, the top-level pages change so infrequently (perhaps never) that it’s not worth it for me to introduce and maintain code that will take up cycles & headspace and perhaps never be used. If you implement such a system in your own repo, I’ll happily link to it in the readme since I’m sure others would be interested.
