### ISSUE TITLE
features from try-pollen in thenotepad?

### ISSUE THREAD

**Issue by jbshirk** [otherjoel/thenotepad#5]
Hi, this isn't really an issue, but a question. 

First off, I have spent many weeks reading about Racket, Pollen, Frog, and several other good projects –and then I came across your work! Wow!  I commend you! Taking all this time to evaluate the respective pros and cons will pay off. The Notepad is practically everything I have in mind.

- It's book-like but can handle an index of new bloggy posts
- It's beautiful (I share  your and Mathew Butterick's love for tasteful typography and ergonomic UI)
- The ergonomic sidenotes and footnotes and your improvement of their contents are wonderful
- The ability to collect many-to-many relationships
- The make part of the generation should grant ways to manage a site hosted on ipfs.io and its content-addressed links. This distributed hosting capability will be the focus of my first site. 

I've already installed the dependencies for both thenotepad and try-pollen and I decided to go with thenotepad and try to add to it things from try-pollen and beautiful-racket that might have not made it into thenotepad. I do like the left column chapter indexes seen in Beautiful Racket and I like the top previous and next links in one of your e-books.

So for example, on my second site (the raison d'être of the first), I want that ability to group by series that's in try-pollen. I wondered whether topics tagging in thenotepad is an evolved abstraction of that. 

I have similar use-cases for separate groupings, such as glossary (similar to the docs links in Beautiful Racket), "people" (researchers who have metadata but are not necessarily authors) -for example in radio interviews involving several people in a roundtable, etc.

Your work with Matthew on multi-target will permit me to export subtitle files, one of the important goals of my site.

I wondered about the nifty fonts (E. Tufte) and its CSS used in The Local Yarn and your other gorgeous e-books. Are the CSS's going to be incompatible with each other or the HTML generation templates?

Well, that's a lot to ask. But I promise I will eventually be able to contribute to documentation, especially from a novice's perspective. I already have notes piling up on some Latex gotchas with OSX.

Do you prefer this kind of question on the Google group?

**Comment by otherjoel** [comment]
Hi, thanks for the kind words! I have tried to parse out your questions, let me know if I missed anything.

> I wondered whether topics tagging in thenotepad is an evolved abstraction of that.

“Topics” in this project are a simple tagging functionality. The “series” in try-pollen are a prototype of another idea, sort of like blog “categories” but with content and properties (i.e. Pollen ‘docs‘ and ‘metas’) of their own. Neither is an evolution of the other; they are just two different ways of organizing content that I have experimented with.

> Are the CSS's going to be incompatible with each other or the HTML generation templates?

The HTML markup produced by the two projects is different, and the CSS in each is specific to the markup and structure used by each. So you probably won’t be able to cut and paste from one to the other. But if you know CSS it’s certainly possible to try and adapt features from one to the other.

More generally: The Notepad and the try-pollen projects are quite separate. They both use Pollen, but I started with very different aims for each one, and those aims drove all the design choices. So I have no need or notion of taking design choices from one and “porting” them to the other; each already has the feature set it needs for my uses. Anyone else is welcome to have a go at it, of course!

> Do you prefer this kind of question on the Google group?

For questions about making adaptations to `thenotepad` so it can be re-purposed for your own uses (an activity I encourage!), it’s probably best to email rather than open an issue. I have a full time job and a family and am a very pokey writer, so I don’t always have time to develop detailed responses. But the more specific the question(s), the easier it makes things for me 🙂

If you have a question that specifically involves Pollen in any way, then the Pollen google group is a great place; everyone there is very helpful. And if/when you do publish a site using Pollen, please announce it there as well!

**Comment by jbshirk** [comment]
Thank you for the response!
